### ISSUE TITLE
Make it avaliable on npm or bower

### ISSUE THREAD

**Issue by teles** [JoeKarlsson/angular-instafeed#2]
Hello, why dont you make this repo able to be installed using bower or npm? It would be useful for other projects =)

**Comment by JoeKarlsson** [comment]
That's an awesome idea. I'll try to get it added to NPM later this week. :sparkles:

**Comment by JoeKarlsson** [comment]
I have finished working on an NPM package - I am going to finish writing up the readme, and I will be updating this package later today.

**Comment by teles** [comment]
Nice, @JoeKarlsson1  :D

**Comment by JoeKarlsson** [comment]
Alright - I have added it to [NPM](https://www.npmjs.com/package/angular-instafeed), and I [included a sample build project](https://github.com/JoeKarlsson1/Angular-Instafeed/tree/npm_example) to help you get it all setup. 

Let me know if you have any issues or if you want me to add any additional features. :+1: 

-Joe
